-----------------------
-- Up
-----------------------

INSERT INTO entries VALUES(1,'Abiotrophia spp.');
INSERT INTO entries VALUES(2,'Actinomyces spp.');
INSERT INTO entries VALUES(3,'Arcanobacterium haemolyticum');
INSERT INTO entries VALUES(4,'Bacillus anthracis');
INSERT INTO entries VALUES(5,'Bacillus cereus');
INSERT INTO entries VALUES(6,'Clostridioides difficile / Clostridium difficile');
INSERT INTO entries VALUES(7,'Clostridium botulinum');
INSERT INTO entries VALUES(8,'Clostridium perfringens');
INSERT INTO entries VALUES(9,'Clostridium tetani');
INSERT INTO entries VALUES(10,'Corynebacterium diphtheriae');
INSERT INTO entries VALUES(11,'Enterococcus faecalis');
INSERT INTO entries VALUES(12,'Enterococcus faecium');
INSERT INTO entries VALUES(13,'Erysipelothrix rhusiopathiae');
INSERT INTO entries VALUES(14,'Gardnerella vaginalis');
INSERT INTO entries VALUES(15,'Granulicatella spp.');
INSERT INTO entries VALUES(16,'Group C streptococcus');
INSERT INTO entries VALUES(17,'Group G streptococcus');
INSERT INTO entries VALUES(18,'Leuconostoc spp.');
INSERT INTO entries VALUES(19,'Listeria monocytogenes');
INSERT INTO entries VALUES(20,'Methicillin-resistant Staphylococcus aureus (MRSA);');
INSERT INTO entries VALUES(21,'Methicillin-susceptible Staphylococcus aureus (MSSA);');
INSERT INTO entries VALUES(22,'Mycobacterium leprae');
INSERT INTO entries VALUES(23,'Mycobacterium tuberculosis');
INSERT INTO entries VALUES(24,'Nocardia spp.');
INSERT INTO entries VALUES(25,'Rhodococcus equi');
INSERT INTO entries VALUES(26,'Staphylococcus capitis');
INSERT INTO entries VALUES(27,'Staphylococcus epidermidis');
INSERT INTO entries VALUES(28,'Staphylococcus hominis');
INSERT INTO entries VALUES(29,'Staphylococcus lugdunensis');
INSERT INTO entries VALUES(30,'Streptococcus agalactiae / Group B streptococcus');
INSERT INTO entries VALUES(31,'Streptococcus anginosus group / Streptococcus milleri group');
INSERT INTO entries VALUES(32,'Streptococcus gallolyticus / Streptococcus bovis');
INSERT INTO entries VALUES(33,'Streptococcus iniae');
INSERT INTO entries VALUES(34,'Streptococcus mitis');
INSERT INTO entries VALUES(35,'Streptococcus mutans');
INSERT INTO entries VALUES(36,'Streptococcus pneumoniae');
INSERT INTO entries VALUES(37,'Streptococcus pyogenes / Group A streptococcus');
INSERT INTO entries VALUES(38,'Streptococcus sanguis');
INSERT INTO entries VALUES(39,'Streptococcus suis');
INSERT INTO entries VALUES(40,'Tropheryma whipplei');
INSERT INTO entries VALUES (41,'Acinetobacter spp.');
INSERT INTO entries VALUES (42,'Aggregatibacter actinomycetemcomitans');
INSERT INTO entries VALUES (43,'Aggregatibacter aphrophilus');
INSERT INTO entries VALUES (44,'Anaplasma spp.');
INSERT INTO entries VALUES (45,'Bacteroides fragilis');
INSERT INTO entries VALUES (46,'Bartonella bacilliformis');
INSERT INTO entries VALUES (47,'Bartonella henselae');
INSERT INTO entries VALUES (48,'Bartonella quintana');
INSERT INTO entries VALUES (49,'Bordetella pertusssis');
INSERT INTO entries VALUES (50,'Borrelia burgdorferi');
INSERT INTO entries VALUES (51,'Borrelia recurrentis');
INSERT INTO entries VALUES (52,'Brucella spp.');
INSERT INTO entries VALUES (53,'Burkholderia cepacia');
INSERT INTO entries VALUES (54,'Burkholderia pseudomallei');
INSERT INTO entries VALUES (55,'Campylobacter jejuni');
INSERT INTO entries VALUES (56,'Capnocytophaga canimorsus');
INSERT INTO entries VALUES (57,'Cardiobacterium hominis');
INSERT INTO entries VALUES (58,'Chlamydia trachomatis');
INSERT INTO entries VALUES (59,'Chlamydophila pneumoniae / Chlamydia pneumoniae');
INSERT INTO entries VALUES (60,'Citrobacter spp.');
INSERT INTO entries VALUES (61,'Coxiella burnetii');
INSERT INTO entries VALUES (62,'Edwardsiella spp.');
INSERT INTO entries VALUES (63,'Ehrlichia spp.');
INSERT INTO entries VALUES (64,'Eikenella corrodens');
INSERT INTO entries VALUES (65,'Elizabethkingia spp.');
INSERT INTO entries VALUES (66,'Enterobacter spp.');
INSERT INTO entries VALUES (67,'Escherichia coli');
INSERT INTO entries VALUES (68,'Finegoldia magna');
INSERT INTO entries VALUES (69,'Francisella tularensis');
INSERT INTO entries VALUES (70,'Fusobacterium spp.');
INSERT INTO entries VALUES (71,'Haemophilus ducreyi');
INSERT INTO entries VALUES (72,'Haemophilus influenzae');
INSERT INTO entries VALUES (73,'Haemophilus parainfluenzae');
INSERT INTO entries VALUES (74,'Hafnia alvei');
INSERT INTO entries VALUES (75,'Helicobacter pylori');
INSERT INTO entries VALUES (76,'Kingella kingae');
INSERT INTO entries VALUES (77,'Klebsiella granulomatis');
INSERT INTO entries VALUES (78,'Klebsiella oxytoca');
INSERT INTO entries VALUES (79,'Klebsiella pneumoniae');
INSERT INTO entries VALUES (80,'Klebsiella variicola');
INSERT INTO entries VALUES (81,'Legionella pneumophila');
INSERT INTO entries VALUES (82,'Leptospira spp.');
INSERT INTO entries VALUES (83,'Moraxella catarrhalis');
INSERT INTO entries VALUES (84,'Morganella morganii');
INSERT INTO entries VALUES (85,'Mycobacterium abscessus');
INSERT INTO entries VALUES (86,'Mycobacterium avium complex');
INSERT INTO entries VALUES (87,'Mycobacterium kansasii');
INSERT INTO entries VALUES (88,'Mycobacterium leprae');
INSERT INTO entries VALUES (89,'Mycobacterium marinum');
INSERT INTO entries VALUES (90,'Mycoplasma genitalium');
INSERT INTO entries VALUES (91,'Mycoplasma hominis');
INSERT INTO entries VALUES (92,'Mycoplasma pneumoniae');
INSERT INTO entries VALUES (93,'Neisseria gonorrhoeae');
INSERT INTO entries VALUES (94,'Neisseria meningitidis');
INSERT INTO entries VALUES (95,'Orientia tsutsugamushi');
INSERT INTO entries VALUES (96,'Parvimonas micra');
INSERT INTO entries VALUES (97,'Pasteurella spp.');
INSERT INTO entries VALUES (98,'Peptoniphilus spp.');
INSERT INTO entries VALUES (99,'Prevotella spp.');
INSERT INTO entries VALUES (100,'Proteus spp.');
INSERT INTO entries VALUES (101,'Providencia spp.');
INSERT INTO entries VALUES (102,'Pseudomonas aeruginosa');
INSERT INTO entries VALUES (103,'Rickettsia africae');
INSERT INTO entries VALUES (104,'Rickettsia akari');
INSERT INTO entries VALUES (105,'Rickettsia conorii');
INSERT INTO entries VALUES (106,'Rickettsia parkeri');
INSERT INTO entries VALUES (107,'Rickettsia philipii');
INSERT INTO entries VALUES (108,'Rickettsia prowazekii');
INSERT INTO entries VALUES (109,'Rickettsia rickettsii');
INSERT INTO entries VALUES (110,'Rickettsia typhi');
INSERT INTO entries VALUES (111,'Salmonella spp.');
INSERT INTO entries VALUES (112,'Serratia marcescens');
INSERT INTO entries VALUES (113,'Shigella spp.');
INSERT INTO entries VALUES (114,'Spirillum minus');
INSERT INTO entries VALUES (115,'Stenotrophomonas maltophilia');
INSERT INTO entries VALUES (116,'Streptobacillus moniliformis');
INSERT INTO entries VALUES (117,'Treponema carateum');
INSERT INTO entries VALUES (118,'Treponema pallidum endemicum');
INSERT INTO entries VALUES (119,'Treponema pallidum pallidum');
INSERT INTO entries VALUES (120,'Treponema pallidum pertenue');
INSERT INTO entries VALUES (121,'Ureaplasma parvum');
INSERT INTO entries VALUES (122,'Ureaplasma urealyticum');
INSERT INTO entries VALUES (123,'Veillonella spp.');
INSERT INTO entries VALUES (124,'Vibrio cholerae');
INSERT INTO entries VALUES (125,'Vibrio parahemolyticus');
INSERT INTO entries VALUES (126,'Vibrio vulnificus');
INSERT INTO entries VALUES (127,'Yersinia enterocolitica');
INSERT INTO entries VALUES (128,'Yersinia pestis / Pasteurella pestis');
INSERT INTO entries VALUES (129,'Yersinia pseudotuberculosis');
INSERT INTO entries VALUES (130,'Adenovirus');
INSERT INTO entries VALUES (131,'Astrovirus');
INSERT INTO entries VALUES (132,'BK virus');
INSERT INTO entries VALUES (133,'Chikungunya virus');
INSERT INTO entries VALUES (134,'Cowpox virus');
INSERT INTO entries VALUES (135,'Coxsackievirus');
INSERT INTO entries VALUES (136,'Crimean-Congo hemorrhagic fever virus');
INSERT INTO entries VALUES (137,'Cytomegalovirus (CMV);');
INSERT INTO entries VALUES (138,'Dengue virus');
INSERT INTO entries VALUES (139,'Eastern equine encephalitis virus');
INSERT INTO entries VALUES (140,'Ebola virus');
INSERT INTO entries VALUES (141,'Echovirus');
INSERT INTO entries VALUES (142,'Enterovirus');
INSERT INTO entries VALUES (143,'Epstein-Barr virus (EBV);');
INSERT INTO entries VALUES (144,'Hantavirus');
INSERT INTO entries VALUES (145,'Hendra virus');
INSERT INTO entries VALUES (146,'Hepatitis A virus');
INSERT INTO entries VALUES (147,'Hepatitis B virus');
INSERT INTO entries VALUES (148,'Hepatitis C virus');
INSERT INTO entries VALUES (149,'Hepatitis D virus');
INSERT INTO entries VALUES (150,'Hepatitis E virus');
INSERT INTO entries VALUES (151,'Herpes simplex virus (HSV);');
INSERT INTO entries VALUES (152,'Herpes B virus');
INSERT INTO entries VALUES (153,'Human herpes virus 6 (HHV-6);');
INSERT INTO entries VALUES (154,'Human herpes virus 7 (HHV-7);');
INSERT INTO entries VALUES (155,'Human herpes virus 8 (HHV-8 / Kaposi sarcoma-associated herpesvirus);');
INSERT INTO entries VALUES (156,'Human immunodeficiency virus (HIV);');
INSERT INTO entries VALUES (157,'Human metapneumovirus (HMPV);');
INSERT INTO entries VALUES (158,'Human papillomavirus (HPV);');
INSERT INTO entries VALUES (159,'Human T-cell leukemia virus type 1 (HTLV-1);');
INSERT INTO entries VALUES (160,'Human T-cell leukemia virus type 2 (HTLV-2);');
INSERT INTO entries VALUES (161,'Influenza virus');
INSERT INTO entries VALUES (162,'Jamestown Canyon virus');
INSERT INTO entries VALUES (163,'Japanese encephalitis virus');
INSERT INTO entries VALUES (164,'JC virus');
INSERT INTO entries VALUES (165,'La Crosse virus');
INSERT INTO entries VALUES (166,'Lymphocytic choriomeningitis virus (LCMV);');
INSERT INTO entries VALUES (167,'Marburg virus');
INSERT INTO entries VALUES (168,'Measles virus');
INSERT INTO entries VALUES (169,'Middle East Respiratory Syndrome coronavirus (MERS-CoV);');
INSERT INTO entries VALUES (170,'Molluscum contagiosum virus');
INSERT INTO entries VALUES (171,'Monkeypox virus');
INSERT INTO entries VALUES (172,'Mumps virus');
INSERT INTO entries VALUES (173,'Nipah virus');
INSERT INTO entries VALUES (174,'Norovirus');
INSERT INTO entries VALUES (175,'Orf virus');
INSERT INTO entries VALUES (176,'Parainfluenza virus');
INSERT INTO entries VALUES (177,'Parapovirus');
INSERT INTO entries VALUES (178,'Parechovirus');
INSERT INTO entries VALUES (179,'Parvovirus B19');
INSERT INTO entries VALUES (180,'Picobirnavirus');
INSERT INTO entries VALUES (181,'Poliovirus');
INSERT INTO entries VALUES (182,'Puumala virus');
INSERT INTO entries VALUES (183,'Rabies virus');
INSERT INTO entries VALUES (184,'Respiratory syncytial virus (RSV);');
INSERT INTO entries VALUES (185,'Rhinovirus');
INSERT INTO entries VALUES (186,'Rift Valley fever virus');
INSERT INTO entries VALUES (187,'Rotavirus');
INSERT INTO entries VALUES (188,'Rubella virus');
INSERT INTO entries VALUES (189,'Severe acute respiratory syndrome coronavirus 1 / SARS-CoV-1');
INSERT INTO entries VALUES (190,'Severe acute respiratory syndrome coronavirus 2 / SARS-CoV-2');
INSERT INTO entries VALUES (191,'Severe fever thrombocytopenia syndrome virus (SFTSV);');
INSERT INTO entries VALUES (192,'Smallpox virus');
INSERT INTO entries VALUES (193,'Saint Louis Encephalitis virus');
INSERT INTO entries VALUES (194,'Varicella zoster virus (VZV);');
INSERT INTO entries VALUES (195,'West Nile virus');
INSERT INTO entries VALUES (196,'Western equine encephalitis virus');
INSERT INTO entries VALUES (197,'Yellow fever virus');
INSERT INTO entries VALUES (198,'Zika virus');
INSERT INTO entries VALUES (199,'Aspergillus spp.');
INSERT INTO entries VALUES (200,'Blastomyces spp.');
INSERT INTO entries VALUES (201,'Candida albicans');
INSERT INTO entries VALUES (202,'Candida auris');
INSERT INTO entries VALUES (203,'Candida glabrata');
INSERT INTO entries VALUES (204,'Candida kruei');
INSERT INTO entries VALUES (205,'Candida lusitaniae');
INSERT INTO entries VALUES (206,'Candida parapsilosis');
INSERT INTO entries VALUES (207,'Candida tropicalis');
INSERT INTO entries VALUES (208,'Cladophialophora carrionii');
INSERT INTO entries VALUES (209,'Coccidioides spp.');
INSERT INTO entries VALUES (210,'Cryptococcus gattii');
INSERT INTO entries VALUES (211,'Cryptococcus neoformans');
INSERT INTO entries VALUES (212,'Cunninghamella spp.');
INSERT INTO entries VALUES (213,'Dermatophyte spp.');
INSERT INTO entries VALUES (214,'Exerohilum rostratum');
INSERT INTO entries VALUES (215,'Exophiala spp.');
INSERT INTO entries VALUES (216,'Fonsecaea pedrosoi');
INSERT INTO entries VALUES (217,'Fusarium spp.');
INSERT INTO entries VALUES (218,'Histoplasma capsulatum');
INSERT INTO entries VALUES (219,'Lacazia loboi');
INSERT INTO entries VALUES (220,'Lichtheimia spp.');
INSERT INTO entries VALUES (221,'Lomentospora prolificans');
INSERT INTO entries VALUES (222,'Malassezia spp.');
INSERT INTO entries VALUES (223,'Mucor spp.');
INSERT INTO entries VALUES (224,'Paracoccidioides spp.');
INSERT INTO entries VALUES (225,'Penicillium marneffei');
INSERT INTO entries VALUES (226,'Phialophora verrucosa');
INSERT INTO entries VALUES (227,'Pneumocystis carinii / Pneumocystis jirovecii');
INSERT INTO entries VALUES (228,'Pseudoallescheria boydii');
INSERT INTO entries VALUES (229,'Rhinocladiella aquaspersa');
INSERT INTO entries VALUES (230,'Rhizomucor spp.');
INSERT INTO entries VALUES (231,'Rhizopus spp.');
INSERT INTO entries VALUES (232,'Scedosporium apiospermum');
INSERT INTO entries VALUES (233,'Sporothrix schenkii');
INSERT INTO entries VALUES (234,'Talaromyces marneffei / Penicillium marneffei');
INSERT INTO entries VALUES (235,'Trichophyton spp.');
INSERT INTO entries VALUES (236,'Acanthamoeba');
INSERT INTO entries VALUES (237,'Ancylostoma');
INSERT INTO entries VALUES (238,'Angiostrongylus');
INSERT INTO entries VALUES (239,'Anisakis');
INSERT INTO entries VALUES (240,'Ascaris');
INSERT INTO entries VALUES (241,'Babesia');
INSERT INTO entries VALUES (242,'Balamuthia');
INSERT INTO entries VALUES (243,'Balantioides');
INSERT INTO entries VALUES (244,'Baylisascaris');
INSERT INTO entries VALUES (245,'Clonorchis');
INSERT INTO entries VALUES (246,'Cryptosporidium');
INSERT INTO entries VALUES (247,'Cyclospora');
INSERT INTO entries VALUES (248,'Cystoisospora');
INSERT INTO entries VALUES (249,'Dibiothriocephalus');
INSERT INTO entries VALUES (250,'Dientamoeba');
INSERT INTO entries VALUES (251,'Dracunculus');
INSERT INTO entries VALUES (252,'Echinococcus');
INSERT INTO entries VALUES (253,'Entamoeba');
INSERT INTO entries VALUES (254,'Enterobius');
INSERT INTO entries VALUES (255,'Fasciola');
INSERT INTO entries VALUES (256,'Giardia');
INSERT INTO entries VALUES (257,'Gnathostoma');
INSERT INTO entries VALUES (258,'Leishmania');
INSERT INTO entries VALUES (259,'Loa');
INSERT INTO entries VALUES (260,'Naegleria');
INSERT INTO entries VALUES (261,'Necator');
INSERT INTO entries VALUES (262,'Onchocerca');
INSERT INTO entries VALUES (263,'Opisthorchis');
INSERT INTO entries VALUES (264,'Paragonimus');
INSERT INTO entries VALUES (265,'Plasmodium');
INSERT INTO entries VALUES (266,'Plasmodium');
INSERT INTO entries VALUES (267,'Plasmodium');
INSERT INTO entries VALUES (268,'Plasmodium');
INSERT INTO entries VALUES (269,'Plasmodium');
INSERT INTO entries VALUES (270,'Sarcoptes');
INSERT INTO entries VALUES (271,'Schistosoma');
INSERT INTO entries VALUES (272,'Strongyloides');
INSERT INTO entries VALUES (273,'Taenia');
INSERT INTO entries VALUES (274,'Taenia');
INSERT INTO entries VALUES (275,'Toxocara');
INSERT INTO entries VALUES (276,'Toxoplasma');
INSERT INTO entries VALUES (277,'Trichinella');
INSERT INTO entries VALUES (278,'Trichomonas');
INSERT INTO entries VALUES (279,'Trichuris');
INSERT INTO entries VALUES (280,'Trypanosoma');
INSERT INTO entries VALUES (281,'Trypanosoma');
INSERT INTO entries VALUES (282,'Trypanosoma');
INSERT INTO entries VALUES (283,'Wuchereria');
INSERT INTO tags VALUES (1,'Gram Positive Bacteria');
INSERT INTO tags VALUES (2,'Gram Negative Bacteria');
INSERT INTO tags VALUES (3,'Viruses');
INSERT INTO tags VALUES (4,'Fungi');
INSERT INTO tags VALUES (5,'Parasites');
INSERT INTO entry_tag_map VALUES (1,1);
INSERT INTO entry_tag_map VALUES (2,1);
INSERT INTO entry_tag_map VALUES (3,1);
INSERT INTO entry_tag_map VALUES (4,1);
INSERT INTO entry_tag_map VALUES (5,1);
INSERT INTO entry_tag_map VALUES (6,1);
INSERT INTO entry_tag_map VALUES (7,1);
INSERT INTO entry_tag_map VALUES (8,1);
INSERT INTO entry_tag_map VALUES (9,1);
INSERT INTO entry_tag_map VALUES (10,1);
INSERT INTO entry_tag_map VALUES (11,1);
INSERT INTO entry_tag_map VALUES (12,1);
INSERT INTO entry_tag_map VALUES (13,1);
INSERT INTO entry_tag_map VALUES (14,1);
INSERT INTO entry_tag_map VALUES (15,1);
INSERT INTO entry_tag_map VALUES (16,1);
INSERT INTO entry_tag_map VALUES (17,1);
INSERT INTO entry_tag_map VALUES (18,1);
INSERT INTO entry_tag_map VALUES (19,1);
INSERT INTO entry_tag_map VALUES (20,1);
INSERT INTO entry_tag_map VALUES (21,1);
INSERT INTO entry_tag_map VALUES (22,1);
INSERT INTO entry_tag_map VALUES (23,1);
INSERT INTO entry_tag_map VALUES (24,1);
INSERT INTO entry_tag_map VALUES (25,1);
INSERT INTO entry_tag_map VALUES (26,1);
INSERT INTO entry_tag_map VALUES (27,1);
INSERT INTO entry_tag_map VALUES (28,1);
INSERT INTO entry_tag_map VALUES (29,1);
INSERT INTO entry_tag_map VALUES (30,1);
INSERT INTO entry_tag_map VALUES (31,1);
INSERT INTO entry_tag_map VALUES (32,1);
INSERT INTO entry_tag_map VALUES (33,1);
INSERT INTO entry_tag_map VALUES (34,1);
INSERT INTO entry_tag_map VALUES (35,1);
INSERT INTO entry_tag_map VALUES (36,1);
INSERT INTO entry_tag_map VALUES (37,1);
INSERT INTO entry_tag_map VALUES (38,1);
INSERT INTO entry_tag_map VALUES (39,1);
INSERT INTO entry_tag_map VALUES (40,1);
INSERT INTO entry_tag_map VALUES (41,2);
INSERT INTO entry_tag_map VALUES (42,2);
INSERT INTO entry_tag_map VALUES (43,2);
INSERT INTO entry_tag_map VALUES (44,2);
INSERT INTO entry_tag_map VALUES (45,2);
INSERT INTO entry_tag_map VALUES (46,2);
INSERT INTO entry_tag_map VALUES (47,2);
INSERT INTO entry_tag_map VALUES (48,2);
INSERT INTO entry_tag_map VALUES (49,2);
INSERT INTO entry_tag_map VALUES (50,2);
INSERT INTO entry_tag_map VALUES (51,2);
INSERT INTO entry_tag_map VALUES (52,2);
INSERT INTO entry_tag_map VALUES (53,2);
INSERT INTO entry_tag_map VALUES (54,2);
INSERT INTO entry_tag_map VALUES (55,2);
INSERT INTO entry_tag_map VALUES (56,2);
INSERT INTO entry_tag_map VALUES (57,2);
INSERT INTO entry_tag_map VALUES (58,2);
INSERT INTO entry_tag_map VALUES (59,2);
INSERT INTO entry_tag_map VALUES (60,2);
INSERT INTO entry_tag_map VALUES (61,2);
INSERT INTO entry_tag_map VALUES (62,2);
INSERT INTO entry_tag_map VALUES (63,2);
INSERT INTO entry_tag_map VALUES (64,2);
INSERT INTO entry_tag_map VALUES (65,2);
INSERT INTO entry_tag_map VALUES (66,2);
INSERT INTO entry_tag_map VALUES (67,2);
INSERT INTO entry_tag_map VALUES (68,2);
INSERT INTO entry_tag_map VALUES (69,2);
INSERT INTO entry_tag_map VALUES (70,2);
INSERT INTO entry_tag_map VALUES (71,2);
INSERT INTO entry_tag_map VALUES (72,2);
INSERT INTO entry_tag_map VALUES (73,2);
INSERT INTO entry_tag_map VALUES (74,2);
INSERT INTO entry_tag_map VALUES (75,2);
INSERT INTO entry_tag_map VALUES (76,2);
INSERT INTO entry_tag_map VALUES (77,2);
INSERT INTO entry_tag_map VALUES (78,2);
INSERT INTO entry_tag_map VALUES (79,2);
INSERT INTO entry_tag_map VALUES (80,2);
INSERT INTO entry_tag_map VALUES (81,2);
INSERT INTO entry_tag_map VALUES (82,2);
INSERT INTO entry_tag_map VALUES (83,2);
INSERT INTO entry_tag_map VALUES (84,2);
INSERT INTO entry_tag_map VALUES (85,2);
INSERT INTO entry_tag_map VALUES (86,2);
INSERT INTO entry_tag_map VALUES (87,2);
INSERT INTO entry_tag_map VALUES (88,2);
INSERT INTO entry_tag_map VALUES (89,2);
INSERT INTO entry_tag_map VALUES (90,2);
INSERT INTO entry_tag_map VALUES (91,2);
INSERT INTO entry_tag_map VALUES (92,2);
INSERT INTO entry_tag_map VALUES (93,2);
INSERT INTO entry_tag_map VALUES (94,2);
INSERT INTO entry_tag_map VALUES (95,2);
INSERT INTO entry_tag_map VALUES (96,2);
INSERT INTO entry_tag_map VALUES (97,2);
INSERT INTO entry_tag_map VALUES (98,2);
INSERT INTO entry_tag_map VALUES (99,2);
INSERT INTO entry_tag_map VALUES (100,2);
INSERT INTO entry_tag_map VALUES (101,2);
INSERT INTO entry_tag_map VALUES (102,2);
INSERT INTO entry_tag_map VALUES (103,2);
INSERT INTO entry_tag_map VALUES (104,2);
INSERT INTO entry_tag_map VALUES (105,2);
INSERT INTO entry_tag_map VALUES (106,2);
INSERT INTO entry_tag_map VALUES (107,2);
INSERT INTO entry_tag_map VALUES (108,2);
INSERT INTO entry_tag_map VALUES (109,2);
INSERT INTO entry_tag_map VALUES (110,2);
INSERT INTO entry_tag_map VALUES (111,2);
INSERT INTO entry_tag_map VALUES (112,2);
INSERT INTO entry_tag_map VALUES (113,2);
INSERT INTO entry_tag_map VALUES (114,2);
INSERT INTO entry_tag_map VALUES (115,2);
INSERT INTO entry_tag_map VALUES (116,2);
INSERT INTO entry_tag_map VALUES (117,2);
INSERT INTO entry_tag_map VALUES (118,2);
INSERT INTO entry_tag_map VALUES (119,2);
INSERT INTO entry_tag_map VALUES (120,2);
INSERT INTO entry_tag_map VALUES (121,2);
INSERT INTO entry_tag_map VALUES (122,2);
INSERT INTO entry_tag_map VALUES (123,2);
INSERT INTO entry_tag_map VALUES (124,2);
INSERT INTO entry_tag_map VALUES (125,2);
INSERT INTO entry_tag_map VALUES (126,2);
INSERT INTO entry_tag_map VALUES (127,2);
INSERT INTO entry_tag_map VALUES (128,2);
INSERT INTO entry_tag_map VALUES (129,2);
INSERT INTO entry_tag_map VALUES (130,3);
INSERT INTO entry_tag_map VALUES (131,3);
INSERT INTO entry_tag_map VALUES (132,3);
INSERT INTO entry_tag_map VALUES (133,3);
INSERT INTO entry_tag_map VALUES (134,3);
INSERT INTO entry_tag_map VALUES (135,3);
INSERT INTO entry_tag_map VALUES (136,3);
INSERT INTO entry_tag_map VALUES (137,3);
INSERT INTO entry_tag_map VALUES (138,3);
INSERT INTO entry_tag_map VALUES (139,3);
INSERT INTO entry_tag_map VALUES (140,3);
INSERT INTO entry_tag_map VALUES (141,3);
INSERT INTO entry_tag_map VALUES (142,3);
INSERT INTO entry_tag_map VALUES (143,3);
INSERT INTO entry_tag_map VALUES (144,3);
INSERT INTO entry_tag_map VALUES (145,3);
INSERT INTO entry_tag_map VALUES (146,3);
INSERT INTO entry_tag_map VALUES (147,3);
INSERT INTO entry_tag_map VALUES (148,3);
INSERT INTO entry_tag_map VALUES (149,3);
INSERT INTO entry_tag_map VALUES (150,3);
INSERT INTO entry_tag_map VALUES (151,3);
INSERT INTO entry_tag_map VALUES (152,3);
INSERT INTO entry_tag_map VALUES (153,3);
INSERT INTO entry_tag_map VALUES (154,3);
INSERT INTO entry_tag_map VALUES (155,3);
INSERT INTO entry_tag_map VALUES (156,3);
INSERT INTO entry_tag_map VALUES (157,3);
INSERT INTO entry_tag_map VALUES (158,3);
INSERT INTO entry_tag_map VALUES (159,3);
INSERT INTO entry_tag_map VALUES (160,3);
INSERT INTO entry_tag_map VALUES (161,3);
INSERT INTO entry_tag_map VALUES (162,3);
INSERT INTO entry_tag_map VALUES (163,3);
INSERT INTO entry_tag_map VALUES (164,3);
INSERT INTO entry_tag_map VALUES (165,3);
INSERT INTO entry_tag_map VALUES (166,3);
INSERT INTO entry_tag_map VALUES (167,3);
INSERT INTO entry_tag_map VALUES (168,3);
INSERT INTO entry_tag_map VALUES (169,3);
INSERT INTO entry_tag_map VALUES (170,3);
INSERT INTO entry_tag_map VALUES (171,3);
INSERT INTO entry_tag_map VALUES (172,3);
INSERT INTO entry_tag_map VALUES (173,3);
INSERT INTO entry_tag_map VALUES (174,3);
INSERT INTO entry_tag_map VALUES (175,3);
INSERT INTO entry_tag_map VALUES (176,3);
INSERT INTO entry_tag_map VALUES (177,3);
INSERT INTO entry_tag_map VALUES (178,3);
INSERT INTO entry_tag_map VALUES (179,3);
INSERT INTO entry_tag_map VALUES (180,3);
INSERT INTO entry_tag_map VALUES (181,3);
INSERT INTO entry_tag_map VALUES (182,3);
INSERT INTO entry_tag_map VALUES (183,3);
INSERT INTO entry_tag_map VALUES (184,3);
INSERT INTO entry_tag_map VALUES (185,3);
INSERT INTO entry_tag_map VALUES (186,3);
INSERT INTO entry_tag_map VALUES (187,3);
INSERT INTO entry_tag_map VALUES (188,3);
INSERT INTO entry_tag_map VALUES (189,3);
INSERT INTO entry_tag_map VALUES (190,3);
INSERT INTO entry_tag_map VALUES (191,3);
INSERT INTO entry_tag_map VALUES (192,3);
INSERT INTO entry_tag_map VALUES (193,3);
INSERT INTO entry_tag_map VALUES (194,3);
INSERT INTO entry_tag_map VALUES (195,3);
INSERT INTO entry_tag_map VALUES (196,3);
INSERT INTO entry_tag_map VALUES (197,3);
INSERT INTO entry_tag_map VALUES (198,3);
INSERT INTO entry_tag_map VALUES (199,4);
INSERT INTO entry_tag_map VALUES (200,4);
INSERT INTO entry_tag_map VALUES (201,4);
INSERT INTO entry_tag_map VALUES (202,4);
INSERT INTO entry_tag_map VALUES (203,4);
INSERT INTO entry_tag_map VALUES (204,4);
INSERT INTO entry_tag_map VALUES (205,4);
INSERT INTO entry_tag_map VALUES (206,4);
INSERT INTO entry_tag_map VALUES (207,4);
INSERT INTO entry_tag_map VALUES (208,4);
INSERT INTO entry_tag_map VALUES (209,4);
INSERT INTO entry_tag_map VALUES (210,4);
INSERT INTO entry_tag_map VALUES (211,4);
INSERT INTO entry_tag_map VALUES (212,4);
INSERT INTO entry_tag_map VALUES (213,4);
INSERT INTO entry_tag_map VALUES (214,4);
INSERT INTO entry_tag_map VALUES (215,4);
INSERT INTO entry_tag_map VALUES (216,4);
INSERT INTO entry_tag_map VALUES (217,4);
INSERT INTO entry_tag_map VALUES (218,4);
INSERT INTO entry_tag_map VALUES (219,4);
INSERT INTO entry_tag_map VALUES (220,4);
INSERT INTO entry_tag_map VALUES (221,4);
INSERT INTO entry_tag_map VALUES (222,4);
INSERT INTO entry_tag_map VALUES (223,4);
INSERT INTO entry_tag_map VALUES (224,4);
INSERT INTO entry_tag_map VALUES (225,4);
INSERT INTO entry_tag_map VALUES (226,4);
INSERT INTO entry_tag_map VALUES (227,4);
INSERT INTO entry_tag_map VALUES (228,4);
INSERT INTO entry_tag_map VALUES (229,4);
INSERT INTO entry_tag_map VALUES (230,4);
INSERT INTO entry_tag_map VALUES (231,4);
INSERT INTO entry_tag_map VALUES (232,4);
INSERT INTO entry_tag_map VALUES (233,4);
INSERT INTO entry_tag_map VALUES (234,4);
INSERT INTO entry_tag_map VALUES (235,4);
INSERT INTO entry_tag_map VALUES (236,5);
INSERT INTO entry_tag_map VALUES (237,5);
INSERT INTO entry_tag_map VALUES (238,5);
INSERT INTO entry_tag_map VALUES (239,5);
INSERT INTO entry_tag_map VALUES (240,5);
INSERT INTO entry_tag_map VALUES (241,5);
INSERT INTO entry_tag_map VALUES (242,5);
INSERT INTO entry_tag_map VALUES (243,5);
INSERT INTO entry_tag_map VALUES (244,5);
INSERT INTO entry_tag_map VALUES (245,5);
INSERT INTO entry_tag_map VALUES (246,5);
INSERT INTO entry_tag_map VALUES (247,5);
INSERT INTO entry_tag_map VALUES (248,5);
INSERT INTO entry_tag_map VALUES (249,5);
INSERT INTO entry_tag_map VALUES (250,5);
INSERT INTO entry_tag_map VALUES (251,5);
INSERT INTO entry_tag_map VALUES (252,5);
INSERT INTO entry_tag_map VALUES (253,5);
INSERT INTO entry_tag_map VALUES (254,5);
INSERT INTO entry_tag_map VALUES (255,5);
INSERT INTO entry_tag_map VALUES (256,5);
INSERT INTO entry_tag_map VALUES (257,5);
INSERT INTO entry_tag_map VALUES (258,5);
INSERT INTO entry_tag_map VALUES (259,5);
INSERT INTO entry_tag_map VALUES (260,5);
INSERT INTO entry_tag_map VALUES (261,5);
INSERT INTO entry_tag_map VALUES (262,5);
INSERT INTO entry_tag_map VALUES (263,5);
INSERT INTO entry_tag_map VALUES (264,5);
INSERT INTO entry_tag_map VALUES (265,5);
INSERT INTO entry_tag_map VALUES (266,5);
INSERT INTO entry_tag_map VALUES (267,5);
INSERT INTO entry_tag_map VALUES (268,5);
INSERT INTO entry_tag_map VALUES (269,5);
INSERT INTO entry_tag_map VALUES (270,5);
INSERT INTO entry_tag_map VALUES (271,5);
INSERT INTO entry_tag_map VALUES (272,5);
INSERT INTO entry_tag_map VALUES (273,5);
INSERT INTO entry_tag_map VALUES (274,5);
INSERT INTO entry_tag_map VALUES (275,5);
INSERT INTO entry_tag_map VALUES (276,5);
INSERT INTO entry_tag_map VALUES (277,5);
INSERT INTO entry_tag_map VALUES (278,5);
INSERT INTO entry_tag_map VALUES (279,5);
INSERT INTO entry_tag_map VALUES (280,5);
INSERT INTO entry_tag_map VALUES (281,5);
INSERT INTO entry_tag_map VALUES (282,5);
INSERT INTO entry_tag_map VALUES (283,5);

-----------------------
-- Down
-----------------------

DELETE FROM entry_tag_map;
DELETE FROM entries;
DELETE FROM tags;
